{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "filecodebox.secretName" . }}
  labels:
    {{- include "filecodebox.labels" . | nindent 4 }}
type: Opaque
stringData:
  FCB_JWT_SECRET: {{ include "filecodebox.jwtSecret" . | quote }}
  FCB_ADMIN_PASSWORD: {{ .Values.secret.adminPassword | quote }}
  FCB_PRODUCTION: {{ ternary "1" "0" .Values.secret.production | quote }}
  {{- with .Values.secret.serverMode }}
  FCB_SERVER_MODE: {{ . | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secret.database }}
  FCB_DATABASE_{{ upper $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secret.redis }}
  FCB_REDIS_{{ upper $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.secret.extra }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
